"""empty message

Revision ID: 7bfe6fc8271d
Revises: 75b9437c7af4
Create Date: 2020-10-12 15:17:52.264264

"""
from __future__ import absolute_import, print_function, unicode_literals, division
from alembic import op
import sqlalchemy as sa
from kirin.core.model import (
    DEFAULT_DAYS_TO_KEEP_TRIP_UPDATE,
    DEFAULT_DAYS_TO_KEEP_RT_UPDATE,
    GTFS_RT_DAYS_TO_KEEP_TRIP_UPDATE,
    GTFS_RT_DAYS_TO_KEEP_RT_UPDATE,
)

# revision identifiers, used by Alembic.
revision = "7bfe6fc8271d"
down_revision = "75b9437c7af4"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contributor",
        sa.Column(
            "nb_days_to_keep_rt_update",
            sa.Integer(),
            server_default=str(DEFAULT_DAYS_TO_KEEP_RT_UPDATE),
            nullable=False,
        ),
    )
    op.add_column(
        "contributor",
        sa.Column(
            "nb_days_to_keep_trip_update",
            sa.Integer(),
            server_default=str(DEFAULT_DAYS_TO_KEEP_TRIP_UPDATE),
            nullable=False,
        ),
    )
    connection = op.get_bind()
    connection.execute(
        "update contributor "
        "set nb_days_to_keep_rt_update={}, nb_days_to_keep_trip_update={} "
        "where contributor.connector_type='gtfs-rt'".format(
            GTFS_RT_DAYS_TO_KEEP_RT_UPDATE, GTFS_RT_DAYS_TO_KEEP_TRIP_UPDATE
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contributor", "nb_days_to_keep_trip_update")
    op.drop_column("contributor", "nb_days_to_keep_rt_update")
    # ### end Alembic commands ###
